use_frameworks!

target 'TZSegmentedControl_Example' do
  pod 'TZSegmentedControl', :path => '../'

  target 'TZSegmentedControl_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
