use_frameworks!

target 'TZSegmentedControl_Example' do
  pod 'TZSegmentedControl', :path => '../'

  target 'TZSegmentedControl_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.3.2'
    pod 'Nimble', '~> 7.3.2'
  end
end
